kafka_servers:
  - "127.0.0.1:9093"
kafka_topic_name: "test_topic_1"
database_type: "mongodb"
mongodb:
  db_server: "localhost"
  db_port: 27017
  db_login: "root"
  db_pass: "rootpass"
  db_name: "simple_shop"
  product_table: "products"
  customers_table: "customers"
